spring.r2dbc.url=r2dbc:postgresql://localhost:5432/digitalfactoryhx
spring.r2dbc.username=user
spring.r2dbc.password=password
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql